<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  4202 => 'Praha',
  42031 => 'Středočeský kraj',
  42032 => 'Středočeský kraj',
  42035 => 'Karlovarský kraj',
  42037 => 'Plzeňský kraj',
  42038 => 'Jihočeský kraj',
  42039 => 'Jihočeský kraj',
  42041 => 'Ústecký kraj',
  42046 => 'Pardubický kraj',
  42047 => 'Ústecký kraj',
  42048 => 'Liberecký kraj',
  42049 => 'Královehradecký kraj',
  42051 => 'Jihomoravský kraj',
  42053 => 'Jihomoravský kraj',
  42054 => 'Jihomoravský kraj',
  42055 => 'Moravskoslezský kraj',
  42056 => 'Kraj Vysočina',
  42057 => 'Zlínský kraj',
  42058 => 'Olomoucký kraj',
  42059 => 'Moravskoslezský kraj',
);
